name: Build cross-platform

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libssl-dev libx11-dev
      - name: Configure
        run: cmake -S . -B build -DUSE_OPENSSL=ON
      - name: Build
        run: cmake --build build -j
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileEncryptionDemo-linux
          path: build/FileEncryptionDemo

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenSSL
        run: |
          brew update
          brew install openssl
      - name: Configure
        run: |
          OPENSSL_ROOT=$(brew --prefix openssl)
          cmake -S . -B build -DOPENSSL_ROOT_DIR="$OPENSSL_ROOT"
      - name: Build
        run: cmake --build build -j
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileEncryptionDemo-macos
          path: build/FileEncryptionDemo

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build-win -G "Visual Studio 17 2022" -A x64 -DUSE_OPENSSL=OFF
      - name: Build
        run: cmake --build build-win --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileEncryptionDemo-windows
          path: build-win/Release/FileEncryptionDemo.exe


